name: reviewdog
on: [pull_request]
jobs:
  golint:
    name: golint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Add go/bin
        run: |
          echo ::add-path::$(go env GOPATH)/bin
      - name: Install golint
        run: |
          ( mkdir -p /tmp/golint && cd /tmp/golint && go get golang.org/x/lint/golint )
      - name: Install reviewdog
        run: |
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: golint
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          golint ./... | reviewdog -f=golint -reporter=github-pr-check -name=golint -level=warning
